require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.devicons"
require "user.nvim-tree"
require "user.telescope"
require "user.comment"
require "user.treesitter"
require "user.bufferline"
require "user.lualine"
require "user.spaceduck"

-- TODO: upgrade nvim0.8 with live-preview plugin
